### ISSUE TITLE
boot-cljs does not work with cljs 1.9.198 and onwards

### ISSUE THREAD

**Issue by molst** [adzerk-oss/boot-cljs#133]
I get the cljs compilation error "contains? not supported on type: clojure.lang.PersistentList" when the plumbing.core dependency is compiled.

All versions since the stable release 1.9.198 fails, but prior is OK.

I updated Clojure to the 1.9-alpha11 and boot to 2.6.0 with no luck.

**Comment by Deraen** [comment]
Can you be more specific?

1.9.225 is working fine for me: https://github.com/Deraen/saapas/blob/master/build.boot

**Comment by onetom** [comment]
Works for me too with 1.9.225.
@molst sounds like it's an issue with https://github.com/plumatic/plumbing/blob/master/src/plumbing/core.cljx though `contains?` seems to be a `clojure.core/contains?`

I'm getting an error from a library too, but than again it's not a problem of `boot-cljs`:
```
WARNING: uuid? already refers to: cljs.core/uuid? being replaced by: cognitect.transit/uuid? at line 342 /Users/pair/.boot/cache/tmp/Users/pair/ap/fe/moy/-f94hw9/index.html.out/cognitect/transit.cljs
```

**Comment by molst** [comment]
Sorry, you're right. For some reason I thought boot-cljs was using plumbing, but it was om-bootstrap. boot-cljs is OK
